const COMMUNITY_CHAT = "COMMUNITY_CHAT";
const USER_CONNECTED = "USER_CONNECTED";
const MESSAGE_RECIEVED = "MESSAGE_RECIEVED";
const MESSAGE_SENT = "MESSAGE_SENT";
const USER_DISCONNECTED = "USER_DISCONNECTED";
const TYPING = "TYPING";
const VERIFY_USER = "VERIFY_USER";
const LOGOUT = "LOGOUT";



module.exports = {
	COMMUNITY_CHAT,
	USER_CONNECTED,
	MESSAGE_RECIEVED,
	MESSAGE_SENT,
	USER_DISCONNECTED,
	TYPING,
	VERIFY_USER,
	LOGOUT
}
